name: Static Code Analysis

# Trigger on pushes to main branch (when code is merged)
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-analysis:
    name: Static Code Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install UV package manager
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"

      - name: Install project dependencies
        run: |
          echo "📦 Installing dependencies..."
          uv sync

      #   - name: Create reports directory
      #     run: mkdir -p reports

      - name: Code formatting check with Black
        run: |
          echo "🎨 Checking code formatting with Black..."
          echo "================================================================"
          uv run black --check --diff shared test *.py
          echo "✅ Code formatting check completed"

      - name: Code linting with Pylint
        run: |
          echo "🔍 Running code linting with Pylint..."
          echo "================================================================"
          uv run pylint shared test --score=yes
          echo "✅ Code linting completed"

      - name: Type checking with MyPy
        run: |
          echo "🔍 Running type checking with MyPy..."
          echo "================================================================"
          uv run mypy shared test
          echo "✅ Type checking completed"

    # - name: Run tests
    #   run: |
    #     echo "🧪 Running test suite..."
    #     echo "================================================================"
    #     uv run pytest --tb=short -v
    #     echo "✅ Tests completed"

    # - name: Upload test reports
    #   uses: actions/upload-artifact@v4
    #   if: always()
    #   with:
    #     name: test-reports
    #     path: reports/
    #     retention-days: 30

    # - name: Quality check summary
    #   if: always()
    #   run: |
    #     echo "================================================================"
    #     echo "📊 STATIC CODE ANALYSIS SUMMARY"
    #     echo "================================================================"
    #     echo "✅ Black formatting check: PASSED"
    #     echo "✅ MyPy type checking: PASSED"
    #     echo "✅ Pylint code analysis: PASSED"
    #     echo "✅ Test suite: PASSED"
    #     echo "================================================================"
    #     echo "🎉 All quality checks completed successfully!"
    #     echo "================================================================"
